Vagrant.configure("2") do |config|

  ##################################################
  # Base VM configuration
  ##################################################

  config.vm.box = "debian/bookworm64"

  config.vm.hostname = "data-coven-dev"

  ##################################################
  # VirtualBox resources
  ##################################################

  config.vm.provider "virtualbox" do |vb|
    vb.name = "data-coven-dev"

    vb.memory = 4096
    vb.cpus = 2
  end

  ##################################################
  # Networking
  ##################################################

  config.vm.network "private_network",
    ip: "192.168.56.10"

  ##################################################
  # Bootstrap
  ##################################################

  config.vm.provision "shell", inline: <<-SHELL

    apt-get update
    apt-get install -y git

    git clone --branch dev \
      https://github.com/rob834lewis/data-coven.git \
      /srv/data-coven

    cd /srv/data-coven

    chmod +x scripts/bootstrap_master.sh

    bash scripts/bootstrap_master.sh

  SHELL

end