Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.hostname = "data-coven-dev"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "data-coven-dev"

    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.network "private_network",
    ip: "192.168.56.10"

end